#!/usr/bin/env python
# Function: figure out the lines of codes
# Usage: count (in the root of your project)
# Note: modify the pattern if necessary

import os
import re

pattern = r'^[A-Za-z_]*\.(c|h|asm|inc)$'
total = 0

def PrintDirTree(rootDir, level=1):
    global total
    if level == 1:
        print rootDir
    for lists in os.listdir(rootDir):
        path = os.path.join(rootDir, lists)
        if os.path.isdir(path) and lists[0] != '.':
            print '|  ' * (level - 1) + '|--' + lists
            PrintDirTree(path, level + 1)
        elif re.match(pattern, lists):
            lines = os.popen('wc %s -l' % path).read()[:-len(path) - 2]
            print '|  ' * (level - 1) + '|--' + lists + ' (' + lines + ')'
            total += int(lines)

if __name__ == '__main__':
    PrintDirTree(os.popen('pwd').read()[:-1])
    print 'Total Lines: %d' % total
