#!/bin/sh
# Function: generate the index files of cscope and ctags
# Usage: index (in the root of your project)

find . -name "*.h" -o -name "*.c" -o -name "*.asm" -o -name "*.inc" > cscope.files
cscope -bkq -i cscope.files
/usr/local/bin/ctags -R
