#!/usr/bin/env python
# Function: warn you when execute rm
# Usage: same as the /bin/rm

import os
import sys

if len(sys.argv) > 1:
    guard = raw_input('Are you sure to continue?(Y/N):')
    if guard in ('Y', 'y'):
        os.system('/bin/rm %s' %  ' '.join(sys.argv[1:]))
    elif guard in ('N', 'n'):
        print 'Nothing happened, it saves you this time !'
    else:
        print 'Invalid choice !'
else:
    print os.popen('/bin/rm').read()
